import './globals.css'
import { Nunito_Sans } from 'next/font/google'
import Header from '../components/Header'
import Footer from '../components/Footer'

const nunito = Nunito_Sans({subsets: ['latin']})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children }) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
